import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import localFont from "next/font/local";

const baseFont = localFont({
  variable: "--font-base",
  src: "../../public/fonts/base.woff2",
});
export const baseBoldFont = localFont({
  variable: "--font-base-bold",
  src: "../../public/fonts/base-bold.woff2",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${baseFont.className} `}>
        <section>
          <Header />
        </section>
        <section>{children}</section>
        <section>
          <Footer />
        </section>
      </body>
    </html>
  );
}
